# ============================================================
# This file was generated by cookiecutter-templates/cookies/bootstrap.
# Please do not modify but update the cookiecutter.json and regenerate.
# For example additional resources to terraform should be added through further terraform files instead.
#
# @generated
# @version v3.3.79
# @see https://gitlab.breuni.de/itops/oct/cookiecutter/cookiecutter-templates
# ============================================================

provider "gitlab" {
  base_url = "https://gitlab.breuni.de"
}

locals {
  gitlab_namespace = "itops/oct/pulp"          # set by cookiecutter.gitlab_namespace
  project_slug     = "terraform-provider-pulp" # set by cookiecutter.project_slug
}

import {
  id = format("%s/%s", local.gitlab_namespace, local.project_slug)
  to = module.gitlab_project.gitlab_project.this
}

module "simple_vault_policy" {
  source  = "gitlab.breuni.de/itops/terraform-module-simple-vault-policy/local"
  version = "1.1.0"

  name = format("%s-vault-secrets", local.project_slug)

  read = flatten([
    # Here could be an extension point for vault_read_paths,
    # see https://gitlab.breuni.de/itops/oct/cookiecutter/cookiecutter-templates/-/blob/v3.3.79/README.md#extension-points  editorconfig-checker-disable-line
  ])

  write = flatten([
    format("secret/data/%s/%s/*", local.gitlab_namespace, local.project_slug),
    # Here could be an extension point for vault_write_paths,
    # see https://gitlab.breuni.de/itops/oct/cookiecutter/cookiecutter-templates/-/blob/v3.3.79/README.md#extension-points  editorconfig-checker-disable-line
  ])
}

module "gitlab_project" {
  source = "gitlab.breuni.de/itops/terraform-module-gitlab-project/local"

  version = "3.1.0"

  name        = local.project_slug
  slug        = local.project_slug
  description = "Fetch, upload, organize and distribute Software Packages on-prem." # set by cookiecutter.project_description  editorconfig-checker-disable-line
  namespace   = local.gitlab_namespace
  avatar      = "avatar.png" # set by cookiecutter.gitlab_avatar

  # set by cookiecutter.gitlab_tags
  tags = [
    "pulp",
    "terraform"
  ]

  features = {
    builds_access_level                              = "enabled"
    visibility_level                                 = "internal"
    lfs_enabled                                      = false
    packages_enabled                                 = false
    only_allow_merge_if_all_discussions_are_resolved = true
    only_allow_merge_if_pipeline_succeeds            = true
  }

  policies = flatten([
    module.simple_vault_policy.policy.name,
    # Here could be an extension point for policies,
    # see https://gitlab.breuni.de/itops/oct/cookiecutter/cookiecutter-templates/-/blob/v3.3.79/README.md#extension-points  editorconfig-checker-disable-line
  ])
}
