# ============================================================
# This file was generated by cookiecutter-templates/cookies/bootstrap.
# Please do not modify but update the cookiecutter.json and regenerate.
# For example additional resources to terraform should be added through further terraform files instead.
#
# @generated
# @version v3.3.79
# @see https://gitlab.breuni.de/itops/oct/cookiecutter/cookiecutter-templates
# ============================================================

terraform {
  backend "http" {
    lock_method    = "POST"
    unlock_method  = "DELETE"
    address        = "https://gitlab.breuni.de/api/v4/projects/5825/terraform/state/bootstrap"
    lock_address   = "https://gitlab.breuni.de/api/v4/projects/5825/terraform/state/bootstrap/lock"
    unlock_address = "https://gitlab.breuni.de/api/v4/projects/5825/terraform/state/bootstrap/lock"
  }

  required_version = ">= 1.6"

  required_providers {
    gitlab = {
      source  = "gitlabhq/gitlab"
      version = "18.9.0"
    }
    vault = {
      source  = "hashicorp/vault"
      version = "5.7.0"
    }
    time = {
      source  = "hashicorp/time"
      version = "0.13.1"
    }
  }
}

provider "vault" {
  auth_login_oidc {
    role = "keycloak-user"
  }
}
