---
include:
  - project: "itops/gitlab-ci-templates"
    ref: "v20.7.0"
    file: "generic.gitlab-ci.yml"

# Allow .pre stage to run.
dummy:
  stage: test
  needs: []
  image: docker.io/library/busybox:latest@sha256:1487d0af5f52b4ba31c7e465126ee2123fe3f2305d638e7827681e7cf6c83d5e
  script:
    - echo "Only projects without a real pipeline get this joke"
