---
exclude: '^\.gitlab-ci\.yml$'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: no-commit-to-branch
        args: [--branch, master]
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-added-large-files
      - id: detect-private-key
      - id: end-of-file-fixer
  - repo: https://github.com/editorconfig-checker/editorconfig-checker
    rev: v3.6.1
    hooks:
      - id: editorconfig-checker
        stages:
          - pre-commit
        args:
          - --exclude=^CHANGELOG.md$
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.22.0
    hooks:
      - id: markdownlint-cli2
