# Copyright E. Breuninger GmbH & Co 2026
# SPDX-License-Identifier: MPL-2.0

---
extends: default
rules:
  line-length:
    max: 120
ignore: |
  **/.terraform/*
  **/.github/*
  .golangci.yml
  .goreleaser.yml
